baseURL = "/"
languageCode = "en-GB"
title = "Lotus Docs"
theme = "lotusdocs"
contentDir = "content"
enableEmoji = true

[module]
  # uncomment line below for temporary local development of module
  replacements = "github.com/colinwilson/lotusdocs -> themes/lotusdocs"
  [module.hugoVersion]
    extended = true
    min = "0.100.0"
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false

[params]

  # google_fonts = [
  #   ["Nunito", "300, 400, 600, 700"],
  #   ["Source Code Pro", "500, 700"]
  # ]

  # sans_serif_font = "Nunito"          # Default is System font
  # secondary_font  = "Nunito"          # Default is System font
  # mono_font       = "Source Code Pro" # Default is System font

    [params.footer]
        copyright = "© :YEAR: Lotus Labs. Designed by Colin Wilson"
        version = true # includes git commit info

    [params.social]
            github = "colinwilson/lotusdocs"        # github.com/YOUR_GITHUB_ID
            twitter = "lotusdocs"       # twitter.com/YOUR_TWITTER_ID
            # instagram = "colinwilson"     # instagram.com/YOUR_INSTAGRAM_ID
            # rss = true                    # show rss icon with link

[menu]
# [[menu.primary]]
#     name  = "Docs"
#     url = "/docs"
#     identifier = "docs"
#     weight = 10

# [[menu.primary]]
#     name  = "Showcase"
#     url = "/showcase"
#     identifier = "showcase"
#     weight = 20

[[menu.primary]]
    name  = "Community"
    url = "https://github.com/colinwilson/lotusdocs/discussions"
    identifier = "community"
    weight = 30