name: DocSearch Scraper

on:
  workflow_run:
      workflows: [deploy-production]
      types: [completed]
  push:
    branches:
      - release
    paths:
      - 'content/docs/**'

jobs:
  docsearch_crawler:
    name: DocSearch Crawl & Index
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the content of docsearch.json as config
        id: docsearch-config
        run: echo "::set-output name=config::$(cat docsearch-prod.json | jq -r tostring)"

      - name: Algolia DocSearch Action
        id: algolia
        uses: adapttive/algolia-docsearch-action@1.1.1
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          CONFIG: ${{ steps.docsearch-config.outputs.config }}
